name: Release
on:
  push:
    branches:
      - 'macos-bin'
env:
  GO_VERSION: 1.15.5
  GOPATH: ${{ github.workspace }}/go
  WORKING_DIR: ${{ github.workspace }}/go/src/github.com/ethereum/go-ethereum
jobs:
  build-binary:
    name: 'Build binary for ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ "macos-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Setup Go ${{ env.GO_VERSION }}'
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: 'Prepare environment'
        id: env
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          echo "::set-output name=key::$(go env GOOS)_$(go env GOARCH)"
          echo "::set-output name=version::${GITHUB_REF##*/}"
      - name: 'Check out project files'
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: ${{ env.WORKING_DIR }}
      - name: 'Build geth'
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          upx --version || echo
          make geth
          ./build/bin/geth version
          tar cfvz build/bin/geth_${{ steps.env.outputs.version }}_${{ steps.env.outputs.key }}.tar.gz -C build/bin geth
      - name: 'Upload artifact 1'
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.WORKING_DIR }}/build/bin/geth
          name: ${{ steps.env.outputs.key }}
          if-no-files-found: error
      - name: 'Upload artifact 2'
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.WORKING_DIR }}/build/bin/geth*.tar.gz
          name: ${{ steps.env.outputs.key }}-tar
          if-no-files-found: error